/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
export interface NonEmptyArray<A> extends Array<A> {
    0: A
}
export type Maybe<T> = null | undefined | T
export type Integer = number
export type JSONDATA = Record<string,any>

export type City = 'A' | 'B' | 'C'
export type Empty = never
