/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
export interface NonEmptyArray<A> extends Array<A> {
  0: A
}

export type MaybeArray<A> = A | Array<A>

/**
 * @since 0.2.0
 */
/**
 * @since 0.2.0
 */
export type City = 'A' | 'B' | 'C'
/**
 * @since 0.2.0
 */
export interface User {
  /**
   * @since 0.2.0
   */
  all: NonEmptyArray<string>
  /**
   * @since 0.2.0
   */
  requireAndArray: Array<number>
  /**
   * @since 0.2.0
   */
  isArrayRequiredAndArray?: NonEmptyArray<number>
  /**
   * @since 0.2.0
   */
  RequiredAndisArrayRequired: NonEmptyArray<number>
  /**
   * @since 0.2.0
   */
  array?: Array<number>
  /**
   * @since 0.2.0
   */
  isArrayRequired?: NonEmptyArray<number>
  /**
   * @since 0.2.0
   */
  require: Date
  /**
   * @since 0.2.0
   */
  empty?: number
}
