/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
export interface NonEmptyArray<A> extends Array<A> {
    0: A
}

export type MaybeArray<A> = A | Array<A>

export type City = 'A' | 'B' | 'C'
export interface User {
  all: NonEmptyArray<string>
  requireAndArray: Array<number>
  isArrayRequiredAndArray?: NonEmptyArray<number>
  RequiredAndisArrayRequired: NonEmptyArray<number>
  array?: Array<number>
  isArrayRequired?: NonEmptyArray<number>
  require: Date
  empty?: number
}


