/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
export interface NonEmptyArray<A> extends Array<A> {
  0: A
}

export type MaybeArray<A> = A | Array<A>

/**
 * @since 0.2.0
 */
/**
 * @since 0.2.0
 */
export type City = 'A' | 'B' | 'C'
/**
 * @since 0.2.0
 */
export type Empty = never
