/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
export interface NonEmptyArray<A> extends Array<A> {
    0: A
}

export type MaybeArray<A> = A | Array<A>

export interface Documentable {
  name: string
  description?: string
  since: string
  deprecated: boolean
  examples: Array<boolean>
}
export interface Interface extends Documentable {
  signature: string
}
export interface Func extends Documentable {
  signature: string
}
export interface Method extends Documentable {
  signature: string
}
export interface Class extends Documentable {
  signature: string
  methods: Array<Method>
  staticMethods: Array<Method>
}
export interface TypeAlias extends Documentable {
  signature: string
}
export interface Constant extends Documentable {
  signature: string
}
export interface Export extends Documentable {
  signature: string
}
export interface Module {
  path: Array<string>
  description?: string
  interfaces: Array<Interface>
  typeAliases: Array<TypeAlias>
  functions: Array<Func>
  classes: Array<Class>
  constants: Array<Constant>
  exports: Array<Export>
  deprecated: boolean
}


