/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
export interface NonEmptyArray<A> extends Array<A> {
  0: A
}

export type MaybeArray<A> = A | Array<A>

/**
 * @since 0.2.0
 */
/**
 * @since 0.2.0
 */
export interface User {
  /**
   * @since 0.2.0
   */
  name: string
  /**
   * @since 0.2.0
   */
  id: string
  /**
   * @since 0.2.0
   */
  age?: number
  /**
   * @since 0.2.0
   */
  female?: boolean
  /**
   * @since 0.2.0
   */
  city: 'dalian' | 'london' | 'newyork' | 'beijing'
}
