/**
 * Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.
 */
import * as t from 'macoolka-io'
/**
 * @since 0.2.0
 */
export const User = t.intersection([
  t.type({
    /**
     * @since 0.2.0
     */
    name: t.string,
    /**
     * @since 0.2.0
     */
    id: t.string,
    /**
     * @since 0.2.0
     */
    city: t.withDefault(t.keyof({ dalian: '', london: '', newyork: '', beijing: '' }), 'dalian')
  }),
  t.partial({
    /**
     * @since 0.2.0
     */
    age: t.int,
    /**
     * @since 0.2.0
     */
    female: t.boolean
  })
])
