export const headerTS = [`Code generated by github.com/macoolka/macoolka-gen-model, DO NOT EDIT.`]
export const importsIO = [`import * as t from 'macoolka-io'`]
export const importsTS = [
    `export interface NonEmptyArray<A> extends Array<A> {
    0: A
}

export type MaybeArray<A> = A | Array<A>
`

]
